-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOqklv/uIEPqX6oXA
3OQPe9MeFuIHIT5RFbUJsYJvY6CgCgYIKoZIzj0DAQehRANCAAT5dzzoeOLLoO6H
Cmvm1/17k7relF/68iib1TRRS1xIXxVvgrK23makJa/KVOd0PxTHAsfHhpSTLPx1
icabfOGM
-----END PRIVATE KEY-----