-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPCEgsFjTolG3WRth
D62CQ8yXtGOuWsKbCy7vym419y+gCgYIKoZIzj0DAQehRANCAARhaEv1Cd1pKdgY
+Y1c1PxzViiNJAApqat6bv3DDeEspydI1DKwaiLJbIoKbmY7vAqWxiv4HCaKpyL4
VusjO1OH
-----END PRIVATE KEY-----