version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: eventosapp-db
    restart: always
    environment:
      POSTGRES_USER: eventosapp_user
      POSTGRES_PASSWORD: eventosapp_password
      POSTGRES_DB: eventosapp
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
